name: GitHub Actions Build Bundle

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Uses Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prep and build bundle
        run: npm ci
      - run: npm run-script build
      - name: Commit bundle
        run: |
          git config --global user.name 'Jaxsbr'
          git config --global user.email 'Jaxsbr@users.noreply.github.com'
          git add -A
          git commit -m "bundle updated"
          git push
