name: GitHub Actions Build Bundle

on: [push]

jobs:
  bundle:
    runs-on: ubuntu-latest            
    steps:
      - uses: actions/checkout@v2      
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run-script build
      - uses: stefanzweifel/git-auto-commit-action@v4
